title: Arquillian
tagline: Write Real Tests
description: The revolutionary integration testing platform for Java and the JVM. Open source. Highly extensible.
# author is used in the atom feed
author: Arquillian Project
#keywords: arquillian,drone,graphene,testing,junit,testng,selenium,javaee,jboss,redhat,openshift,open source
#gem_version: 0.2.7
jira_key: ARQ
ohloh_id: 480465
# use repos_dir to move clones outside of website tree
repos_dir: /tmp/arqrepos
resolve_published_artifacts: false
github_organization: arquillian
source_repo: https://github.com/arquillian
website_source_repo: https://github.com/arquillian/arquillian.github.com
website_source_branch: develop
speakers_team_id: 146647
issue_tracker: https://issues.jboss.org/browse/ARQ
api_docs: http://docs.jboss.org/arquillian/api/latest
spi_docs: http://docs.jboss.org/arquillian/spi/latest
ref_guide: https://docs.jboss.org/author/display/ARQ/Reference+Guide
project_space: http://community.jboss.org/en/arquillian
faqs: http://community.jboss.org/en/arquillian/faq
migration_guides: http://community.jboss.org/wiki/ArquillianMigrationGuides
user_forum: http://community.jboss.org/en/arquillian?view=discussions
dev_forum: http://community.jboss.org/en/arquillian/dev?view=discussions
irc_transcripts: http://transcripts.jboss.org/channel/irc.freenode.org/%23jbosstesting/index.html
haml:
#  format: :html5
  attr_wrapper: '"'
disqus_generate_id: true
profiles:
  debug:
    show_debug: true
  development:
  sandbox:
    base_url: http://sandbox.arquillian.org:4242
    disqus: arquillian-sandbox
    disqus_developer: true
  staging:
    base_url: http://arqpreview-alrubinger.rhcloud.com
    google_analytics: UA-18727998-4
    disqus: arquillian-staging
    resolve_published_artifacts: true
  production:
    base_url: http://arquillian.org
    google_analytics: UA-18727998-3
    disqus: arquillian
    resolve_published_artifacts: true
    evolvecache: true
